### ISSUE TITLE
Opening binary VOTables

### ISSUE THREAD

**Issue by astrozot** [malapert/JsVotable#2]
In the examples provided with the library it is clearly stated how to open standard VOTables, with a tabledata part, but it is not stated how to deal with binary or binary2 VOTables:
```
// gets the data : it could be tabledata, fits, binary or binary2
var data = table.getData();
if (data!=null && data.getDataImplementationName() == JsVotable.TAG.TABLEDATA) {
    var tabledata = data.getData();
    var trs = tabledata.getTrs();    
}
```
Is it possible to open the data parts of these files? If it is, what is the way to do it?

**Comment by malapert** [comment]
Yes it should be possible, look at the tests :
https://github.com/malapert/JsVotable/blob/97a485644a58fe0a7668ed1515a38a3a96478294/test/votable.js#L149-L159

Let me know if it works
